### ISSUE TITLE
Problem with configuring Git Bash to Run Python

### ISSUE THREAD

**Issue by AnushPetrosyan** [HiLearn-University/ml101-2020#3]
Hi all. 
I successfully installed Git in my pc (Windows), but while runing the following in my Command Prompt, I get this printed   "  'source' is not recognized as an internal or external command "․

echo 'export PATH="$PATH:"/c/Users/User/Anaconda3":"/c/Users/User/Anaconda3/Scripts" '  >> .bashrc
echo 'alias python="winpty python.exe"' >> .bashrc
source .bashrc

Please can you help me to fix a ploblem with configuring Git Bash to Run Python. I'm not sure, Is the written path right, or maybe I should type it in Bit Bash terminal instead of writing in Command Prompt?

Thanks in advance.

**Comment by Vahan2000** [comment]
Yes, you should run it in Git Bash terminal.

**Comment by Vahan2000** [comment]
Updated the [documentation](https://github.com/HiLearn-University/ml101-2020/blob/master/docs/python.md#install-anaconda-on-windows)

**Comment by mamikonyana** [comment]
9caeb874513f24f3e5e2943370564477eceb1456

**Comment by AnushPetrosyan** [comment]
Thank you very much!!
I am new to Git and Github, please can you also take a look into the path below. Is the syntax right?

 echo 'export PATH="$PATH:/c/Users/USER:/c/Users/USER/Anaconda3/Scripts"' >> .bashrc

After running this 
conda --version
python -version

it returns the version of conda (conda 4.7.12) , but for python returns the following error.
winpty: error: cannot start 'python.exe': Not found in PATH

**Comment by Vahan2000** [comment]
Did you run this command `echo 'alias python="winpty python.exe"' >> .bashrc` ?

**Comment by Vahan2000** [comment]
You should have run `echo 'export PATH="$PATH:/c/Users/USER/Anaconda3:/c/Users/USER/Anaconda3/Scripts"' >> .bashrc`.
To fix this run `rm -rf .bashrc` to remove .bashrc. And then run all the commands in Git Bash terminal from the beginning.

**Comment by mamikonyana** [comment]
you should also replace `USER` with your actual username on your computer

**Comment by AnushPetrosyan** [comment]
Thank you very much,, it worked
